version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=${AUTH_URL:-http://localhost:3000}
      - PROJECT_GROUP_ID=${PROJECT_GROUP_ID}
      - BASE_URL=${BASE_URL:-http://localhost:3000}
      - PROXY_BASE_URL=${PROXY_BASE_URL:-http://localhost:3000}
      - HOST=${HOST:-localhost:3000}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mobile-web:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - EXPO_PUBLIC_BASE_URL=${EXPO_PUBLIC_BASE_URL:-http://localhost:3000}
      - EXPO_PUBLIC_PROXY_BASE_URL=${EXPO_PUBLIC_PROXY_BASE_URL:-http://localhost:3000}
      - EXPO_PUBLIC_PROJECT_GROUP_ID=${PROJECT_GROUP_ID}
      - EXPO_PUBLIC_HOST=${HOST:-localhost:3000}
    restart: unless-stopped
    depends_on:
      - web